name: Main Report Update

on:
  push:
    branches-ignore:
    - '!main' # Push events to branches matching allure-report
    paths-ignore:
    - 'history/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: 
  contents: write

jobs:
  main-check:
    concurrency: report

    environment: 
      name: report
      url: https://nanlabs.github.io/automation-seed

    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.18.1"

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies without generating a lockfile and fail if an update is needed
        run: yarn --frozen-lockfile

      - name: Run e2e tests
        run: yarn test:remote --suite ci.report
        env:
          OUTPUT_DIR: "../../logs"
          WEBDRIVER_LOGLEVEL: info
          MAX_INSTANCES: 3
          CHROME: 2
          WEBDRIVER_SPEC_FILE_RETRIES: 1

      - name: Save history
        if: always()
        # trying to save history of previous runs if it exists
        run: cp -r $(pwd)/docs/history/. $(pwd)/allure-results/history || true

      - name: Create report
        if: always()
        run: yarn report --clean

      - name: Update history
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: allure-report
          path: ./allure-report

      - name: Deploy report
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        if: always()
        with:
          branch: main # The branch the action should deploy to.
          folder: allure-report # The folder the action should deploy.
          target-folder: docs

      - name: Create Artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: result
          if-no-files-found: warn
          path: |
            logs
            test/errors
            test/reports
