name: Pull Request Validation

on:
  pull_request:
    branches:
      - main

jobs:
  lint-check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3

      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '14.15.1'

      - name: Use cached node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies without generating a lockfile and fail if an update is needed
        run: yarn --frozen-lockfile

      - name: Run Eslint validation
        run: yarn lint

  run-e2e-tests:
    needs: 'lint-check'
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3

      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '14.18.1'

      - name: Use cached node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies without generating a lockfile and fail if an update is needed
        run: yarn --frozen-lockfile

      - name: Run tests for PR
        run: yarn test:remote --suite ci.pull_request
        env:
          OUTPUT_DIR: '../../logs'
          CHROME: 2

      - name: Create Artifact
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: result
          if-no-files-found: warn
          path: |
            ~/.aerokube/selenoid
            logs
            allure-results
            allure-report
